export const LOAD_TOURNEYS_REQUEST = "LOAD_TOURNEYS_REQUEST";
export const LOAD_TOURNEYS_SUCCESS = "LOAD_TOURNEYS_SUCCESS";
export const LOAD_TOURNEYS_FAIL = "LOAD_TOURNEYS_FAIL";

export const LOAD_TOURNEY_REQUEST = "LOAD_TOURNEY_REQUEST";
export const LOAD_TOURNEY_SUCCESS = "LOAD_TOURNEY_SUCCESS";
export const LOAD_TOURNEY_FAIL = "LOAD_TOURNEY_FAIL";
